services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"  
    volumes:
      - .:/app  
    environment:
      - ENVIRONMENT=development  
    depends_on:
      - db  
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - app_network  

  db:
    image: postgres:15  
    restart: always  
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: mydatabase  
    volumes:
      - pgdata_cloud:/var/lib/postgresql/data  
    networks:
      - app_network 
  
  pgadmin:
    image: dpage/pgadmin4  
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  
    depends_on:
      - db  
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: npm run dev
    depends_on:
      - app
    networks:
      - app_network

volumes:
  pgdata_cloud:  

networks:
  app_network:
    driver: bridge  
